version: '3.8'



services:
  backend:
    build: .
    container_name: golfstore-backend
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - golfnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5433/golfshop
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Potetb0dil
      KC_DB_SCHEMA: keycloak
    networks:
      - golfnet

networks:
  golfnet:

